### ISSUE TITLE
Prisma CLI "db push --preview-feature" command doesn't seem to work with Docker

### ISSUE THREAD

**Issue by quavious** [prisma/prisma-client-go#377] opened 2021-01-27 08:17 UTC
I am trying to goecho-prisma-psql server using Docker Toolbox in Windows 10.

The structure of my project is below

```
📂 goecho-prisma-psql
  📂 go-server
    📂 prisma
        📂 db
        🧾 prisma.schema
    🧾 main.go
    🧾 go.mod
    🧾 go.sum
    🧾 Dockerfile
 📂 nextjs-client
 🧾 docker-compose.yml
```

I have written the Dockerfile of golang server like this

```Dockerfile
FROM ubuntu:latest
FROM golang as builder
RUN apt update
RUN mkdir /go/src/app
ADD . /go/src/app
WORKDIR /go/src/app
RUN go install github.com/quavious/golang-prisma-board
RUN ["go", "run", "github.com/prisma/prisma-client-go", "db", "push", "--preview-feature"]
RUN ["go", "run", "github.com/prisma/prisma-client-go", "generate"]
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

RUN apk add --no-cache ca-certificates && update-ca-certificates

EXPOSE 5000

CMD [ "go", "run", "." ]
# CMD ["./main"] # This statement is also not working.
``` 

The file docker-compose.wml

```docker-compose.yml
version: "3"
services:
  api:
    build:
      context: ./go-server
    working_dir: /go/src/app
    ports:
      - "5000:5000"
    volumes:
      - ./volumes
    environment:
      DB_ADDRESS: postgresql://postgres:<DB_PASSWORD>@db/<DB_NAME>?<DB_PARAMETER>

  db: # this service name is also used to DB_HOST
    restart: always
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_NAME
```

DB_HOST is "db" that is same with the name of the service db.

When i enter the command "docker-compose up" or "docker-compose run api", go and go package is normally installed, but server container is stopped immediately.

The message from terminal is this.
```powershell
info: 2021/01/27 07:08:04 prisma cli fetched successfully.
Error: P1001: Can't reach database server at `db`:`5432`

Please make sure your database server is running at `db`:`5432`.

goroutine 1 [running]:
main.main()
        /go/pkg/mod/github.com/prisma/prisma-client-go@v0.2.0/main.go:29 +0x493
exit status 2
ERROR: Service 'api' failed to build: The command 'go run github.com/prisma/prisma-client-go db push --preview-feature' returned a non-zero code: 1
``` 

I don't know what is the problem, but it looks like this matter is related with the command "go run github.com/prisma/prisma-client-go db push --preview-feature"

Can i execute go and prisma in docker container?

I am using ubuntu as the OS in my container, not alpine linux.

**Comment by steebchen** [comment] 2021-01-27 14:00
Can you please share your schema, or at least the first few lines with the config blocks?

**Comment by quavious** [comment] 2021-01-27 14:47
Prisma Schema
```schema.prisma
generator db {
  provider = "go run github.com/prisma/prisma-client-go"
}

datasource db {
  provider = "postgresql"
  url      = env("DB_ADDRESS")
}

model Product {
  id         String    @id
  createdAt  DateTime  @default(now())
  updatedAt  DateTime  @updatedAt
  name       String
  poster     String
  company    String
  percent    Int
  base_price Int
  discounted Int
  adLink     String
  expiredAt  DateTime?
  Category   Category? @relation(fields: [categoryId], references: [id])
  categoryId Int?
}

model Category {
  id         Int        @id @default(autoincrement())
  value      String     @unique
  categories Category[] @relation("CategoryToCategory")
  Category   Category?  @relation("CategoryToCategory", fields: [categoryId], references: [id])
  categoryId Int?
  products   Product[]
}

model Post {
  id        Int       @id @default(autoincrement())
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  user      String
  userIP    String
  password  String
  isAdmin   Boolean   @default(false)
  title     String
  content   String
  adLink    String
  comments  Comment[]
}

model Comment {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  isDeleted Boolean  @default(false)
  user      String
  userIP    String
  password  String
  content   String
  Post      Post?    @relation(fields: [postId], references: [id])
  postId    Int?
}

model Forbidden {
  id      Int    @id @default(autoincrement())
  valueIP String
}

model Admin {
  id       Int    @id @default(autoincrement())
  email    String @unique
  password String
}
```

environment variables in the file .env or docker-compose-yml

```.env
POSTGRES_USER: postgres
POSTGRES_PASSWORD: <password>
POSTGRES_DB: <db_name>

DB_ADDRESS: postgresql://postgres:<password>@db/<db_name>?parseTime=True
```

The name of database host is "db" which is same with the docker service "db".

Commands which i have tried 

```powershell
docker-compose up
docker-compose run db AND docker-compose run api
```

**Comment by steebchen** [comment] 2021-01-27 14:55
Ah, I think I know what the problem is. You're using env vars, but env vars are used for the docker image at runtime, not for the build process.

First, I don't recommend to use `db push` in the docker file. You should run that locally only, preferably not in docker (except if you have a good reason).

Second, if you really want to do that, I think what you want to use is a docker build arg using `ARG FOO` in your docker file and using the `build.args` syntax for compose.

**Comment by quavious** [comment] 2021-01-27 18:24
Because Prisma Client Go is not at stable version , It is seem that Prisma cli is not working perfectly in docker machine.
Thanks. I have confirmed what you have informed
Can you close this issue?

**Comment by steebchen** [comment] 2021-01-27 18:28
I kindly disagree – while the Go client is still in a very early phase, the command works fine; even in docker. In your case it looks like the env var wasn't even there, which means the error you got makes a lot of sense.

I'll go ahead and close this issue – if there's something still not working, please feel free to re-open.

**Closed by steebchen** 2021-01-27 18:28 UTC
Labels: kind/question
