### ISSUE TITLE
Chaining relations

### ISSUE THREAD

**Issue by matthewmueller** [prisma/prisma-client-go#198] opened 2020-07-16 11:15 UTC
**Problem**

JS Client supports chained relations, but the Go client does not

```js
const postsByUser: Post[] = await prisma.user
  .findOne({ where: { email: 'alice@prisma.io' } })
  .posts()
```

**Suggested Solution**

```go
posts, err := client.User.FindOne(...).Posts(...).Exec(ctx)
```

**Comment by steebchen** [comment] 2020-07-16 13:46
duplicate of https://github.com/prisma/prisma-client-go/issues/104 and was abandoned due to https://github.com/prisma/prisma-client-go/issues/104#issuecomment-624567858

**Closed** 2020-07-16 15:28 UTC
Labels: kind/feature
